title:            ITC571 Blog - jmckay13
description:      <Temporary Description>

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             edit.svg # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://itc571.jmckay13.website

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'

# Owner/author information
owner:
  name:           James McKay
  site:           http://itc514.jmckay13.website
  avatar:         images/avatar.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
  email:          you@email.com
  # GitHub nick for use in follow button in author block.
  github: portablejim

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/NSW
locale:      en_AU
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

float_share: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
#theme: neo-hpstr-jekyll-theme
    #### Welcome to Jekyll!
    ####
    #### This config file is meant for settings that affect your whole blog, values
    #### which you are expected to set up once and rarely edit after that. If you find
    #### yourself editing this file very often, consider using Jekyll's data files
    #### feature for the data you need to update frequently.
    ####
    #### For technical reasons, this file is *NOT* reloaded automatically when you use
    #### 'bundle exec jekyll serve'. If you change this file, please restart the server process.
    ###
    #### Site settings
    #### These are used to personalize your new site. If you look in the HTML files,
    #### you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
    #### You can create any custom variable you would like, and they will be accessible
    #### in the templates via {{ site.myvariable }}.
    ###title: Your awesome title
    ###email: your-email@domain.com
    ###description: > # this means to ignore newlines until "baseurl:"
    ###  Write an awesome description for your new site here. You can edit this
    ###  line in _config.yml. It will appear in your document head meta (for
    ###  Google search results) and in your feed.xml site description.
    ###baseurl: "" # the subpath of your site, e.g. /blog
    ###url: "" # the base hostname & protocol for your site, e.g. http://example.com
    ###twitter_username: jekyllrb
    ###github_username:  jekyll
    ###
    #### Build settings
    ###markdown: kramdown
    ###theme: minima
    ###gems:
    ###  - jekyll-feed
    ###exclude:
    ###  - Gemfile
    ###  - Gemfile.lock
